[tools]
python = "3.14"
uv = "latest"

[tasks.start]
run = "uv run behind-the-bastards --host 127.0.0.1 --port 8000"

[tasks.update-dataset]
run = "uv run python scripts/archive_btb.py"

[tasks.ruff]
run = "uv run ruff check"
[tasks.ty]
run = "uv run ty check"
[tasks.test]
run = "uv run pytest"

[tasks.check]
depends = ["ruff", "ty", "test"]
